export { default as LeftHand } from './LeftHand'
export { default as RightHand } from './RightHand'
export { default as Logo } from './Logo'
export { Midi } from './Midi'
export * from 'react-feather'
