export default {
  // Lines
  staff5Lines: '\uE014',
  staff5LinesNarrow: '\uE020',
  legerLine: '\uE022',

  fClef: '\uE062',
  gClef: '\uE050',
  brace: '\uE000',
  timeSig0: '\uE080',
  timeSig1: '\uE081',
  timeSig2: '\uE082',
  timeSig3: '\uE083',
  timeSig4: '\uE084',
  timeSig5: '\uE085',
  timeSig6: '\uE086',
  timeSig7: '\uE087',
  timeSig8: '\uE088',
  timeSig9: '\uE089',
  timeSigCombNumerator: '\uE09E',
  timeSigCombDenominator: '\uE09F',

  noteheadBlack: '\uE0A4',
  noteEmptyBlack: '\uE1AF',
  noteAFlatBlack: '\uE196',
  noteABlack: '\uE197',
  noteASharpBlack: '\uE198',
  noteBFlatBlack: '\uE199',
  noteBBlack: '\uE19A',
  noteBSharpBlack: '\uE19B',
  noteCFlatBlack: '\uE19C',
  noteCBlack: '\uE19D',
  noteCSharpBlack: '\uE19E',
  noteDFlatBlack: '\uE19F',
  noteDBlack: '\uE1A0',
  noteDSharpBlack: '\uE1A1',
  noteEFlatBlack: '\uE1A2',
  noteEBlack: '\uE1A3',
  noteESharpBlack: '\uE1A4',
  noteFFlatBlack: '\uE1A5',
  noteFBlack: '\uE1A6',
  noteFSharpBlack: '\uE1A7',
  noteGFlatBlack: '\uE1A8',
  noteGBlack: '\uE1A9',
  noteGSharpBlack: '\uE1AA',

  // Staff ligatures for lowering/raising.
  staffPosLower1: '\uEB98',
  staffPosLower2: '\uEB99',
  staffPosLower3: '\uEB9A',
  staffPosLower4: '\uEB9B',
  staffPosLower5: '\uEB9C',
  staffPosLower6: '\uEB9D',
  staffPosLower7: '\uEB9E',
  staffPosLower8: '\uEB9F',
  staffPosRaise1: '\uEB90',
  staffPosRaise2: '\uEB91',
  staffPosRaise3: '\uEB92',
  staffPosRaise4: '\uEB93',
  staffPosRaise5: '\uEB94',
  staffPosRaise6: '\uEB95',
  staffPosRaise7: '\uEB96',
  staffPosRaise8: '\uEB97',

  // Accidentals
  accidentalFlat: '\uE260',
  accidentalNatural: '\uE261',
  accidentalSharp: '\uE262',
  accidentalDoubleSharp: '\uE263',
  accidentalDoubleFlat: '\uE264',
}
